keys:
  # Users
  - &users:
    - &saviohc age19xa5u3rmqrsymy22rty6v9ldjxn7xrujg6cj9qfe7ky32y8y8sts644h5j
  # Hosts
  - &hosts:
    - &chrono age19xa5u3rmqrsymy22rty6v9ldjxn7xrujg6cj9qfe7ky32y8y8sts644h5j
    - &majora age132qmztydp7l5tn99vz7drn7a6shvkypwaa2z9t234tp63qw65pdqs3ewxt
    # Add cyrus and ohana

creation_rules:
  # By host
  - path_regex: hosts/chrono/secrets.yaml$
    key_groups:
      - age:
        - *chrono

  - path_regex: hosts/majora/secrets.yaml$
    key_groups:
      - age:
        - *majora

  # Common 
  - path_regex: hosts/common/secrets.yaml$
    key_groups:
      - age:
        - *chrono
        - *majora
  
  # Users
  - path_regex: hosts/common/users/secrets.yaml$
    key_groups:
      - age:
        - *chrono
        - *majora
