# A staring point is the basic NIXOS configuration generated by the ISO installer.
# On an existing NIXOS install you can use the following command in your flakes basedir:
# sudo nixos-generate-config --dir ./hosts/m3tam3re
#
# Please make sure to change the first couple of lines in your configuration.nix:
# { config, inputs, ouputs, lib, pkgs, ... }:
#
# {
#   imports = [ # Include the results of the hardware scan.
#     ./hardware-configuration.nix
#     inputs.home-manager.nixosModules.home-manager
#   ];
#   ...
#
# Moreover please update the packages option in your user configuration and add the home-manager options:
# users.users = {
#   m3tam3re = {
#     isNormalUser = true;
#     initialPassword = "12345";
#     extraGroups = [ "wheel" ]; # Enable ‘sudo’ for the user.
#     packages = [ inputs.home-manager.packages.${pkgs.system}.default ];
#   };
# };
#
# home-manager = {
#   useUserPackages = true;
#   extraSpecialArgs = { inherit inputs outputs; };
#   users.m3tam3re =
#     import ../../home/m3tam3re/${config.networking.hostName}.nix;
# };
#
# Please also change your hostname accordingly:
# networking.hostName = "nixos"; # Define your hostname.
{
  imports = [
    ../common/global
    ../common/optional/video.nix
    ../common/optional/prime.nix
    ../common/optional/containers
    ../common/optional/kubernetes
    ../common/optional/incus
    ./configuration.nix];

  video.enable = true;
  video.environment= "hyprland";

  oci-config = {
    enable = true;
    engine = "podman";
    rootless = false;
    updates.enable = false;
  };

  kubernetes = {
    enable = false;
    distro = "kind";
  };
  
  incus = {
    enable = true;
    config = {
      config = {
        "core.https_address" = "[::]:8443";
      };
      networks = [
        {
          config = {
            "ipv4.address" = "10.0.100.1/24";
            "ipv4.nat" = "true";
          };
          name = "incusbr0";
          type = "bridge";
        }
      ];
      profiles = [
        {
          devices = {
            eth0 = {
              name = "eth0";
              network = "incusbr0";
              type = "nic";
            };
            root = {
              path = "/";
              pool = "default";
              size = "35GiB";
              type = "disk";
            };
          };
          name = "default";
        }
      ];
      storage_pools = [
        {
          config = {
            source = "/var/lib/incus/storage-pools/default";
          };
          driver = "dir";
          name = "default";
        }
      ];
    };
  };

  # Keyboard Remap Config
  services.xremap = {
    enable = true;
    userName = "saviohc";
    withHypr = true;
    config = {
      modmap = [
        {
          name = "default";
          remap = {
            "KEY_RIGHTSHIFT" = "KEY_BACKSPACE";
            "SHIFT_R" = "BACKSPACE";
          };
          mode = "default";
        }
      ];
      default_mode = "default";
    };
  };

  networking.firewall.trustedInterfaces = [ "incusbr0" ];

  services.tailscale.enable = true;
  environment.etc.hosts.mode = "0700";
}
